basePath: /v1/transfer
host: localhost:8111
info:
  contact:
    email: support@swagger.io
    name: 这里写联系人信息
    url: http://www.swagger.io/support
  description: 不同系统之间账户资产划转
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 资产划转
  version: "1.0"
paths:
  /confirmtransfer:
    post:
      consumes:
      - application/json
      description: 资产划转确认
      parameters:
      - description: orderid
        in: path
        name: orderid
        required: true
        type: string
      - description: 是否成功
        in: path
        name: success
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: 资产划转确认
      tags:
      - asset 相关接口
  /getCoinAvailablequantity:
    post:
      consumes:
      - application/json
      description: 获取对方系统可用资产
      parameters:
      - description: 用户id
        in: path
        name: customerid
        required: true
        type: string
      - description: 币种id
        in: path
        name: coin
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: 获取对方系统可用资产
      tags:
      - asset 相关接口
  /transferassets:
    post:
      consumes:
      - application/json
      description: 资产划转
      parameters:
      - description: 用户token
        in: path
        name: token
        required: true
        type: string
      - description: 币种id
        in: path
        name: coin
        required: true
        type: string
      - description: orderid
        in: path
        name: orderid
        required: true
        type: string
      - description: 转账金额
        in: path
        name: amount
        required: true
        type: string
      - description: 转账方向
        in: path
        name: side
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: 资产划转
      tags:
      - asset 相关接口
swagger: "2.0"
