// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gowebapi/business"
)

// Injectors from init_wrie.go:

func InitializeRepository() business.EmployeeRepository {
	employeeRepository := business.ProvideEmployeeRepository()
	return employeeRepository
}

func InitializeService(repo business.EmployeeRepository) business.EmployeeService {
	employeeService := business.ProvideEmployeeService(repo)
	return employeeService
}
