apiVersion: v1
kind: Service
metadata:
  name: swaggerdemo-service
spec:
  type: NodePort
  selector:
    app: swaggerdemo
  ports:
    - port: 8080  # Service 暴露的端口
      targetPort: 8091  # Pod 中容器的端口
      nodePort: 30188  # NodePort 类型时指定的端口范围（30000-32767）
