// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "这里写联系人信息",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/confirmtransfer": {
            "post": {
                "description": "资产划转确认",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "asset 相关接口"
                ],
                "summary": "资产划转确认",
                "parameters": [
                    {
                        "type": "string",
                        "description": "orderid",
                        "name": "orderid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "是否成功",
                        "name": "success",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getCoinAvailablequantity": {
            "post": {
                "description": "获取对方系统可用资产",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "asset 相关接口"
                ],
                "summary": "获取对方系统可用资产",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "customerid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "币种id",
                        "name": "coin",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/transferassets": {
            "post": {
                "description": "资产划转",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "asset 相关接口"
                ],
                "summary": "资产划转",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "币种id",
                        "name": "coin",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "orderid",
                        "name": "orderid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "转账金额",
                        "name": "amount",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "转账方向",
                        "name": "side",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8111",
	BasePath:         "/v1/transfer",
	Schemes:          []string{},
	Title:            "资产划转",
	Description:      "不同系统之间账户资产划转",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
