// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.TransferAsset.Model;

#nullable disable

namespace Project.TransferAsset.Migrations
{
    [DbContext(typeof(TransferContext))]
    partial class TransferContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project.TransferAsset.Model.Entity.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("decimal(28,16)");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CoinId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Drawout")
                        .HasColumnType("decimal(28,16)");

                    b.Property<decimal>("FrozenQuantity")
                        .HasColumnType("decimal(28,16)");

                    b.Property<decimal>("Include")
                        .HasColumnType("decimal(28,16)");

                    b.HasKey("Id");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("Project.TransferAsset.Model.Entity.AssetTransferRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(28,16)");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CoinID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AssetTransferRecord");
                });

            modelBuilder.Entity("Project.TransferAsset.Model.Entity.AssetWasteBook", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(1);

                    b.Property<int>("AssetsWasteBookType")
                        .HasColumnType("int");

                    b.Property<string>("AssociatedOrderId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("decimal(28,16)");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ChangeFrozenQuantity")
                        .HasColumnType("decimal(28,16)");

                    b.Property<decimal>("ChangeQuantity")
                        .HasColumnType("decimal(28,16)");

                    b.Property<string>("CoinId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("FrozenQuantity")
                        .HasColumnType("decimal(28,16)");

                    b.Property<decimal>("OriginalAvailableQuantity")
                        .HasColumnType("decimal(28,16)");

                    b.Property<decimal>("OriginalFrozenQuantity")
                        .HasColumnType("decimal(28,16)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AssetWasteBook");
                });
#pragma warning restore 612, 618
        }
    }
}
